In [3]:
import numpy as np

In [2]:
arr = np.array([10,20,30,40,50])

In [3]:
print(f"Memory occupied by array = {arr.nbytes}")

Memory occupied by array = 40


In [4]:
arr1 = np.zeros(10)
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
arr2 = np.ones(10)
print(arr2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [8]:
arr3 = np.ones(10)
print(arr3*10)

[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


In [9]:
arr4 = np.ones(10)
print(arr4*20)

[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]


In [10]:
arr5 = np.ones(10)
print(arr5*50)

[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


In [15]:
arr6 = np.arange(30,70)
print(arr6)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [16]:
arr7 = np.arange(50,95)
print(arr7)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94]


In [17]:
arr8 = np.arange(20,80,2)
print(arr8)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]


In [21]:
arr8 = np.arange(21,80,2)
print(arr8)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


In [30]:
n1 = np.random.randint(10,40,15)
print(n1)

[38 26 27 33 16 35 27 24 14 24 39 26 32 12 13]


In [29]:
n2 = np.random.randint(30,50,10)
print(n1)

[88 56 57 62 52 77 63 74 79 52 74 80 52 51 86 72 72 69 56 55]


In [28]:
n3 = np.random.randint(50,90,20)
print(n1)

[88 56 57 62 52 77 63 74 79 52 74 80 52 51 86 72 72 69 56 55]


In [31]:
arr9 = np.array([1,2,3,4,5,6])
arr10 = np.array([7,8,9,10,11,12])
print(arr9+arr10)

[ 8 10 12 14 16 18]


In [32]:
print(arr9-arr10)

[-6 -6 -6 -6 -6 -6]


In [33]:
print(arr9/arr10)

[0.14285714 0.25       0.33333333 0.4        0.45454545 0.5       ]


In [34]:
print(arr9*arr10)

[ 7 16 27 40 55 72]


In [44]:
n3 = np.arange(10,22)
n3 = n3.reshape([3,4])
print(n3)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [48]:
n4 = np.array([1,0,0,0,1,0,0,0,1])
n4 = n4.reshape([3,3])
print(n4)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [49]:
n5 = np.array([1,0,0,0,0,0,2,0,0,0,0,0,3,0,0,0,0,0,4,0,0,0,0,0,5])
n5 = n5.reshape([5,5])
print(n5)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [60]:
n6 = np.random.random(9)
n6 = n6.reshape([3,3])
print(n6)

[[0.03888771 0.39418124 0.62300047]
 [0.73550895 0.34265425 0.45363819]
 [0.17767372 0.54071325 0.86164931]]


In [62]:
n6 = np.random.random(9)
#n6 = n6.reshape([2,3,4])
print(n6)

[0.58670251 0.11378891 0.7409353  0.57161847 0.79666226 0.14149434
 0.46620544 0.64143385 0.76480178]


In [65]:
n7 = np.arange(2,11)
n7 = n7.reshape([3,3])
print(n7)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [66]:
n8 = np.arange(10,22)
#n8 = n3.reshape([3,4])
print(n8)

[10 11 12 13 14 15 16 17 18 19 20 21]


In [67]:
arr10 = np.array([1,2,3,4,5,6])
print(arr)

[10 20 30 40 50]


In [5]:
arr = np.array([10,20,30,40,50,60,70,80,90])
print(arr)
print(type(arr))

[10 20 30 40 50 60 70 80 90]
<class 'numpy.ndarray'>


In [4]:
def index(i):
    arr1 = np.array([10,22,30,40,65,34,54])
    arr2 = np.array([11,22,23,44,56,34,54])
    print(arr1)
    print(arr2)
    if arr1[i]==arr2[i]:
        print("both elements are equal")
    elif arr1[i]>=arr2[i]:
        print("arr1 have greater element")
    elif arr1[i]<=arr[2]:
        print("arr2 have gteater element")
        
index(4)

[10 22 30 40 65 34 54]
[11 22 23 44 56 34 54]
arr1 have greater element


In [6]:
arr = np.arange(2,11).reshape(3,3)
print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [7]:
arr = np.arange(12,38)
print(arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [8]:
arr = np.array([10,20,30,40,50])
print(arr[::-1])

[50 40 30 20 10]


In [9]:
arr = np.array([11,22,33,44],dtype=np.float16)
print(arr)
print(f"the data type is {arr.dtype}")

[11. 22. 33. 44.]
the data type is float16


In [10]:
l1 = [1,2,3,4,5,6,7,8,9]
print(f"the list is {l1}")
arr = np.array(l1)
print(f"list converted to array is {arr}")

the list is [1, 2, 3, 4, 5, 6, 7, 8, 9]
list converted to array is [1 2 3 4 5 6 7 8 9]


In [11]:
arr1 = np.array([10,20,30,45,65,32])
arr2 = np.array([2,5,4,6,3,8])
print(arr1%arr2)

[0 0 2 3 2 0]


In [12]:
arr = np.arange(20,50)
print(arr)
arr1 = (arr%3)
print(arr1)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]
[2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1]
